main: com.cavetale.enderball.EnderballPlugin

name: Enderball
version: 0.1
description: Enderball Plugin
api-version: '1.21.10'

author: StarTux
website: https://github.com/StarTux/Enderball

depend:
- Core
- Title
- Fam
- Creative
- Area
- AFK

softdepend: []

commands:

  enderball:
    aliases: [enderballadmin, enderballadm]
    description: Enderball Command
    permission: enderball.admin
    usage: |-
      /enderball

permissions:

  enderball.enderball:
    description: '?'
    default: false

  enderball.admin:
    description: Use /enderball
    default: op
