main: com.cavetale.enderball.EnderballPlugin

name: Enderball
version: 0.1
description: Enderball Plugin
api-version: 1.17

author: StarTux
website: https://github.com/StarTux/Enderball

depend: [Title, WorldEdit, Core, Sidebar]
softdepend: []

commands:

  enderball:
    aliases: [enderballadmin, enderballadm]
    description: Enderball Command
    permission: enderball.admin
    usage: |-
      /enderball

permissions:

  enderball.enderball:
    description: '?'
    default: false

  enderball.admin:
    description: Use /enderball
    default: op
